### ISSUE TITLE
MissingSchema error in get_image_data

### ISSUE THREAD

**Issue by night-crawler** [marteinn/wagtail-alt-generator#8]
Hi.
Thanks you for this wagtail package!

With correct default settings (MS Cognitive), valid key specified and `wagtail==1.9` I get this:
```
requests.exceptions.MissingSchema: Invalid URL
'/media/original_images/Screenshot_20170316_184710_8IGnPyn.png': 
No schema supplied. Perhaps you meant
http:///media/original_images/Screenshot_20170316_184710_8IGnPyn.png?
```
With this fix it works fine:
```
import requests
from wagtail.wagtailcore.models import Site
def get_image_data(image_url):
    site = Site.objects.get(is_default_site=True)
    site_url = site.hostname.rstrip('/')
    image_data = requests.get('{}{}'.format(site_url, image_url))
    if image_data.status_code > 200 and image_data.status_code < 300:
        return None
    return image_data.content
```
Did I made mistake somewhere in config or it is a bug? Thanks!

**Comment by marteinn** [comment]
Hi @night-crawler and thanks for the bug report!

The issue seems to be that `file.url` returns the relative url, instead of absolute. Perhaps defining [MEDIA_URL](https://docs.djangoproject.com/en/1.10/ref/settings/#media-url) can solve your issue.

Regardless, I will look into how the library detects the image. The whole point with uploading binary is to avoid any url/domain issues and clearly this can be done better, since we know the image system path. Will research this issue this weekend and get back to you. And let me know if the `MEDIA_URL` solved your issue :)

**Comment by night-crawler** [comment]
> And let me know if the MEDIA_URL solved your issue 

@marteinn, settings absolute `MEDIA_URL` fixes this problem.

**Comment by marteinn** [comment]
@night-crawler Awesome! Will keep this ticket open until I have investigated using file path instead of url in file binary.

**Comment by marteinn** [comment]
Image files are no longer required to be accessible over http. https://github.com/marteinn/wagtail-alt-generator/commit/5e31ef76b4dc232a8020f1c4cc1ccd8469e19512
